version: "3.4"

# Local compose:
# Test
# docker-compose up
# Daemon
# docker-compose up -d
# Jump in
# docker exec -it stationeers-dedicated bash
# tmux ls
# tmux a

services:
  stationeers-dedicated:
    container_name: stationeers-dedicated
    image: powareverb/stationeers-dedserver:latest
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    environment:
      TZ: 'Pacific/Auckland'
      SERVERNAME: "powareverb-stationeers-dedserver-test"
      SERVERPASSWORD: "supersafepassword"
      PLANETOID: "mars"
      # For testing
      # DONOOP: "true"
    volumes:
      - 'stationeers-data:/home/steam/stationeers-server-dedicated'

volumes:
  stationeers-data:

