version: "3.4"

# Local compose:
# Test
# docker-compose up
# Daemon
# docker-compose up -d
# Jump in
# docker exec -it stationeers-dedicated bash
# tmux ls
# tmux a

services:
  stationeers-dedicated:
    container_name: stationeers-dedicated
    image: powareverb/stationeers-dedserver:latest
    # cap_add:
    #   - NET_ADMIN
    ports:
      # Steam server ports
      - "27015/tcp"
      - "27015/udp"
      - "27020/udp"
      # stationeers server ports
      - "27500:27500/udp"
      - "27501:27501/udp"

    # See the README.md for these under "Environment Variables"
    environment:
      TZ: 'Pacific/Auckland'
      SERVERNAME: "powareverb-stationeers-dedserver-test"
      SERVERPASSWORD: "supersafepassword"
      PLANETOID: "mars"
      SAVENAME: "mars101"
      TMUXDIRECT: "true"
      # For testing
      # DONOOP: "true"
    volumes:
      - 'stationeers-data:/home/steam/stationeers-server-dedicated'

volumes:
  stationeers-data:

